version: "3.9"

services:
   db:
       container_name: "calorieTrecker_db"
       image: "postgres:latest"
       environment:
           POSTGRES_DB: "calorieTrecker_db"
           POSTGRES_USER: "postgres"
           POSTGRES_PASSWORD: "postgres"
           # PGDATA: "/var/lib/postgresql/data/pgdata"
       volumes:
           - ./db-data:/docker-entrypoint-initdb.d
           # - ./db-data/postgres_data:/var/lib/postgresql/data
       ports:
           - "5432:5432"

   pgadmin:
       container_name: "pgadmin"
       image: "dpage/pgadmin4:latest"
       environment:
           PGADMIN_DEFAULT_EMAIL: "email@email.com"
           PGADMIN_DEFAULT_PASSWORD: "password"
       ports:
           - "5050:80"
