version: "3.9"

services:
   db:
       container_name: "calorieTrecker_db"
       image: "postgres:latest"
       environment:
           POSTGRES_DB: "calorieTrecker_db"
           POSTGRES_USER: "postgres"
           POSTGRES_PASSWORD: "postgres"
       volumes:
           - ./db-data:/docker-entrypoint-initdb.d
       ports:
           - "5432:5432"
