-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."meal_times"
(
    "meal_time_id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    "meal_time_name" character varying(50) NOT NULL,
    CONSTRAINT "meal_time_pkey" PRIMARY KEY ("meal_time_id")
);

CREATE TABLE IF NOT EXISTS public.meals
(
    meal_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    "meal_user_id" bigint NOT NULL,
    "meal_product_id" bigint NOT NULL,
    "meal_product_weight" numeric NOT NULL,
    meal_date date NOT NULL,
    "meal_time_id" bigint NOT NULL,
    CONSTRAINT meals_pkey PRIMARY KEY (meal_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    "product_fatsecret_id" bigint,
    "product_user_id" bigint,
    product_name character varying(100) NOT NULL,
    product_calories integer NOT NULL,
    "product_proteins" numeric NOT NULL,
    "product_fats" numeric NOT NULL,
    "product_carbohydrates" numeric NOT NULL,
    "product_is_active" boolean NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    user_name character varying(100) NOT NULL,
    user_login character varying(30) NOT NULL,
    user_password character (68) NOT NULL,
    user_weight numeric NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.meals
    ADD CONSTRAINT "meals_meal_product_id_fkey" FOREIGN KEY ("meal_product_id")
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.meals
    ADD CONSTRAINT "meals_meal_time_id_fkey" FOREIGN KEY ("meal_time_id")
    REFERENCES public."meal_times" ("meal_time_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.meals
    ADD CONSTRAINT "meals_meal_user_id_fkey" FOREIGN KEY ("meal_user_id")
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT "users_user_products" FOREIGN KEY ("product_user_id")
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;