-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."dayTime"
(
    "dayTime_id" bigint NOT NULL,
    "dayTime_name" "char"[] NOT NULL,
    CONSTRAINT "dayTime_pkey" PRIMARY KEY ("dayTime_id")
);

CREATE TABLE IF NOT EXISTS public.meals
(
    meals_id bigint NOT NULL,
    "meals_userId" bigint NOT NULL,
    "meals_productId" bigint NOT NULL,
    "meals_productWeight" numeric NOT NULL,
    meals_date date NOT NULL,
    "meals_timeId" bigint NOT NULL,
    CONSTRAINT meals_pkey PRIMARY KEY (meals_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    products_id bigint NOT NULL,
    "products_fatsecretId" bigint,
    "products_userId" bigint,
    products_name "char"[] NOT NULL,
    products_calories integer NOT NULL,
    "products_ proteins" numeric NOT NULL,
    "products_ fats" numeric NOT NULL,
    "products_ carbohydrates" numeric NOT NULL,
    "products_isActive" boolean NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (products_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigint NOT NULL,
    user_name "char"[] NOT NULL,
    user_login "char"[] NOT NULL,
    user_password "char"[] NOT NULL,
    user_weight numeric NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.meals
    ADD CONSTRAINT "meals_meals_productId_fkey" FOREIGN KEY ("meals_productId")
    REFERENCES public.products (products_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.meals
    ADD CONSTRAINT "meals_meals_timeId_fkey" FOREIGN KEY ("meals_timeId")
    REFERENCES public."dayTime" ("dayTime_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.meals
    ADD CONSTRAINT "meals_meals_userId_fkey" FOREIGN KEY ("meals_userId")
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT "users_usersProducts" FOREIGN KEY ("products_userId")
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;