name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: calorieTrecker_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          PGDATA: /var/lib/postgresql/data/pgdata
        ports:
          - 5432:5432

      pgadmin:
        image: dpage/pgadmin4:latest
        env:
          PGADMIN_DEFAULT_EMAIL: email@email.com
          PGADMIN_DEFAULT_PASSWORD: password
        ports:
           - 5050:80

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17

    - name: Set up Maven
      uses: docker://maven:3.8.3-openjdk-17
      with:
        args: mvn --version

    - name: Run tests for client-calorie-tracker
      working-directory: client-calorie-tracker
      run: mvn test

    - name: Run tests for rest-calorie-tracker
      working-directory: rest-calorie-tracker
      run: mvn test
